# Unity Catalog managed storage — the location the catalog's managed tables live in.
#
# Why this file exists: deploy run 5 created the workspace and then failed at
#
#     cannot create catalog: Metastore storage root URL does not exist.
#
# The metastore is created WITHOUT a storage root (modern UC favours catalog-level storage
# over metastore-level, and `var.metastore_storage_root` is empty by default), so a catalog
# with no `storage_root` of its own has nowhere to put managed tables. Databricks offers a
# "Default Storage" path for this, but it is account-state-dependent and not expressible in
# Terraform — an IaC-only project cannot rely on a catalog someone made in the UI.
#
# So the storage is provisioned explicitly, which is also what a regulated deployment wants:
# the managed tables holding transaction features and case verdicts sit in an S3 bucket we
# own, encrypt, version and can point an auditor at.
#
# The access path is the standard UC three-step: a bucket, an IAM role Databricks assumes
# (with UC's distinctive SELF-ASSUMING trust policy), and a storage credential + external
# location that let the catalog use it.

resource "aws_s3_bucket" "uc_managed" {
  bucket        = "${local.name}-uc-managed-${local.account_id}"
  force_destroy = false
  tags          = { Name = "${local.name}-uc-managed" }
}

resource "aws_s3_bucket_public_access_block" "uc_managed" {
  bucket                  = aws_s3_bucket.uc_managed.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "uc_managed" {
  bucket = aws_s3_bucket.uc_managed.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "uc_managed" {
  bucket = aws_s3_bucket.uc_managed.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "aws:kms"
      # The CMK from infra/aws — the same key the rest of the estate uses, so one key
      # revocation covers the lakehouse too.
      kms_master_key_id = local.aws.kms_key_arn
    }
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "uc_managed" {
  bucket = aws_s3_bucket.uc_managed.id
  rule {
    id     = "expire-noncurrent-versions"
    status = "Enabled"
    filter {}
    noncurrent_version_expiration {
      noncurrent_days = 90
    }
    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }
  depends_on = [aws_s3_bucket_versioning.uc_managed]
}

# ---- The IAM role Unity Catalog assumes ------------------------------------------------
#
# UC's trust policy is unusual: besides trusting Databricks' account with an external id, the
# role must also trust ITSELF. Databricks assumes the role and then re-assumes it internally,
# and a role that cannot assume itself fails validation with a message that does not say so.
# Both data sources below are generated by the provider, so the exact shape is not guessed.
locals {
  uc_role_name = "${local.name}-uc-storage"
}

data "databricks_aws_unity_catalog_assume_role_policy" "this" {
  provider       = databricks.account
  aws_account_id = local.account_id
  role_name      = local.uc_role_name
  external_id    = var.databricks_account_id
}

data "databricks_aws_unity_catalog_policy" "this" {
  provider       = databricks.account
  aws_account_id = local.account_id
  bucket_name    = aws_s3_bucket.uc_managed.id
  role_name      = local.uc_role_name
}

resource "aws_iam_policy" "uc_storage" {
  name   = "${local.uc_role_name}-policy"
  policy = data.databricks_aws_unity_catalog_policy.this.json
}

resource "aws_iam_role" "uc_storage" {
  name               = local.uc_role_name
  assume_role_policy = data.databricks_aws_unity_catalog_assume_role_policy.this.json
  tags               = { Name = local.uc_role_name }
}

resource "aws_iam_role_policy_attachment" "uc_storage" {
  role       = aws_iam_role.uc_storage.name
  policy_arn = aws_iam_policy.uc_storage.arn
}

# Same reason as the workspace cross-account role: Databricks VALIDATES this role by
# assuming it, and IAM is eventually consistent. Without the wait the credential is
# rejected for a role that is entirely correct.
resource "time_sleep" "uc_iam_propagation" {
  depends_on      = [aws_iam_role.uc_storage, aws_iam_role_policy_attachment.uc_storage]
  create_duration = "60s"
}

# ---- Storage credential + external location --------------------------------------------
resource "databricks_storage_credential" "uc" {
  provider = databricks.workspace
  name     = "${local.name}-uc-storage"

  aws_iam_role {
    role_arn = aws_iam_role.uc_storage.arn
  }

  comment       = "Unity Catalog managed storage for ${local.name}."
  force_destroy = true

  depends_on = [databricks_metastore_assignment.this, time_sleep.uc_iam_propagation]
}

resource "databricks_external_location" "uc" {
  provider = databricks.workspace
  name     = "${local.name}-uc-managed"
  url      = "s3://${aws_s3_bucket.uc_managed.id}/managed"

  credential_name = databricks_storage_credential.uc.id
  comment         = "Managed-table root for the ${var.project} catalog."
  force_destroy   = true
}
